//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/WormholeRoot/Cursor/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""TouchInputs"",
            ""id"": ""17cf8c15-36eb-49e7-b919-cc2b147d43ef"",
            ""actions"": [
                {
                    ""name"": ""PlacePortal"",
                    ""type"": ""Value"",
                    ""id"": ""1f008427-32b2-4b26-b977-e16a46b02648"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3438eda3-94e2-4a31-9d36-7bccc3b80900"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlacePortal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchInputs
        m_TouchInputs = asset.FindActionMap("TouchInputs", throwIfNotFound: true);
        m_TouchInputs_PlacePortal = m_TouchInputs.FindAction("PlacePortal", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchInputs
    private readonly InputActionMap m_TouchInputs;
    private List<ITouchInputsActions> m_TouchInputsActionsCallbackInterfaces = new List<ITouchInputsActions>();
    private readonly InputAction m_TouchInputs_PlacePortal;
    public struct TouchInputsActions
    {
        private @PlayerControls m_Wrapper;
        public TouchInputsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlacePortal => m_Wrapper.m_TouchInputs_PlacePortal;
        public InputActionMap Get() { return m_Wrapper.m_TouchInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchInputsActions set) { return set.Get(); }
        public void AddCallbacks(ITouchInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchInputsActionsCallbackInterfaces.Add(instance);
            @PlacePortal.started += instance.OnPlacePortal;
            @PlacePortal.performed += instance.OnPlacePortal;
            @PlacePortal.canceled += instance.OnPlacePortal;
        }

        private void UnregisterCallbacks(ITouchInputsActions instance)
        {
            @PlacePortal.started -= instance.OnPlacePortal;
            @PlacePortal.performed -= instance.OnPlacePortal;
            @PlacePortal.canceled -= instance.OnPlacePortal;
        }

        public void RemoveCallbacks(ITouchInputsActions instance)
        {
            if (m_Wrapper.m_TouchInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchInputsActions @TouchInputs => new TouchInputsActions(this);
    public interface ITouchInputsActions
    {
        void OnPlacePortal(InputAction.CallbackContext context);
    }
}
